### ISSUE TITLE
Unhandled rejection TypeError: Object [object Cursor] has no method 'forEach'

### ISSUE THREAD

**Issue by nelsonic** [thejsj/rethinkdb-chat#1]
Hi @thejsj,

Tried running this project following the instructions in the readme.

The app does boot and I'm able to use it, but see this error in the terminal:

![rethinkdb-chat-unhandled-rejection-typeerror](https://cloud.githubusercontent.com/assets/194400/8408537/e1125bd4-1e68-11e5-920d-c2e9ad194897.png)
## Info:

**Node version**: v0.**12.5** (_latest_)
**OS**: OSX 10.10.3
**RethinkDB Version**: **2.0.3**

Are you aware of this issue? Thanks!

**Comment by thejsj** [comment]
Can you try it out again. I think what happened was that the query use to return an array before (in an earlier version of the driver) and now return a cursor. Feel free to open it again if this doesn't solve the problem. 

Thanks for letting me know!

**Comment by nelsonic** [comment]
@thejsj thanks for the quick response!
All clear! (_no more errors in console_) :+1: 

![rethinkdb-chat-all-clear](https://cloud.githubusercontent.com/assets/194400/8419748/20d1110c-1eb4-11e5-9bd0-427fafbd3f36.png)

**Comment by thejsj** [comment]
Cool! This is a super simple, quick demo, but if you have any feedback on it or on the code, I'd love to hear it.
